---
title: "my_ggplot_theme"
author: "Maddy Enda"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

#Loading libraries

```{r}
library(tidyverse)
library(palmerpenguins)
library(here)

```


#creating a theme
```{r}
View(penguins)


ggplot( data= penguins, aes(x= body_mass_g, y= flipper_length_mm)) +
  geom_point(aes(fill= "navy")) +
theme(title = element_text(size = 12, color = "cyan"),
        plot.background = element_rect(fill = "gray20"),
        panel.background = element_rect(fill = "lightblue"),
        axis.text = element_text(color = "aquamarine"),
        panel.grid.major = element_line(color = "blue"),
        panel.grid.minor = element_line(color = "yellow"),
        
      legend.position = "none"  )
  
```

```{r}
#' Sailboat
#'
#' @return
#' @export
#'
#' @examples
sailboat <- function() {theme(title = element_text(size = 12, color = "cyan"),
        plot.background = element_rect(fill = "gray20"),
        panel.background = element_rect(fill = "lightblue"),
        axis.text = element_text(color = "aquamarine"),
        panel.grid.major = element_line(color = "blue"),
        panel.grid.minor = element_line(color = "yellow"),
        
      legend.position = "none"  )
  }
```

#insert skeleton
```{r}

```

